app:
    resource: '@AppBundle/Controller/'
    type: annotation

recipes:
    type: rest
    resource: AppBundle\Controller\RecipesController

recipes_post:
    path: /recipes
    methods: [POST]
    defaults:
      _controller: AppBundle\Controller\RecipesController:postRecipeAction
      _format: json

users:
  type: rest
  resource: AppBundle\Controller\UserController

users_post:
  path: /users
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\UserController:postUserAction
    _format: json

users_post_recipes:
  path: /users/{user}/recipes
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\UserController:postUserRecipesAction
    _format: json