app:
    resource: '@AppBundle/Controller/'
    type: annotation

recipes:
    type: rest
    resource: AppBundle\Controller\RecipesController

recipes_post:
    path: /recipes
    methods: [POST]
    defaults:
      _controller: AppBundle\Controller\RecipesController:postRecipeAction
      _format: json