app:
    resource: '@AppBundle/Controller/'
    type: annotation

recipes:
    type: rest
    resource: AppBundle\Controller\RecipesController

post_recipes:
    path: /recipes
    methods: [POST]
    defaults:
      _controller: AppBundle\Controller\RecipesController:postRecipeAction
      _format: json

users:
  type: rest
  resource: AppBundle\Controller\UserController

post_users:
  path: /users
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\UserController:postUserAction
    _format: json

post_users_recipes:
  path: /users/{user}/recipes
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\UserController:postUserRecipesAction
    _format: json

post_recipes_ingredients:
  path: /recipes/{recipe}/ingredients
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\RecipesController:postRecipeIngredientsAction
    _format: json

products:
  type: rest
  resource: AppBundle\Controller\ProductController

post_pruduct:
  path: /users/{user}/recipes
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\UserController:postUserRecipesAction
    _format: json

product_types:
  type: rest
  resource: AppBundle\Controller\ProductTypeController

units:
  type: rest
  resource: AppBundle\Controller\UnitController